.PHONY: clean All

All:
	@echo "----------Building project:[ 11_Proxy - Debug ]----------"
	@cd "11_Proxy" && "$(MAKE)" -f  "11_Proxy.mk"
clean:
	@echo "----------Cleaning project:[ 11_Proxy - Debug ]----------"
	@cd "11_Proxy" && "$(MAKE)" -f  "11_Proxy.mk" clean
