.PHONY: clean All

All:
	@echo "----------Building project:[ 15_RAII - Debug ]----------"
	@cd "15_RAII" && "$(MAKE)" -f  "15_RAII.mk"
clean:
	@echo "----------Cleaning project:[ 15_RAII - Debug ]----------"
	@cd "15_RAII" && "$(MAKE)" -f  "15_RAII.mk" clean
