.PHONY: clean All

All:
	@echo "----------Building project:[ 13_Bridge - Debug ]----------"
	@cd "13_Bridge" && "$(MAKE)" -f  "13_Bridge.mk"
clean:
	@echo "----------Cleaning project:[ 13_Bridge - Debug ]----------"
	@cd "13_Bridge" && "$(MAKE)" -f  "13_Bridge.mk" clean
